# Generated by Django 5.2.7 on 2026-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deputy_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
