# Generated by Django 5.2.7 on 2026-02-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_is_deputy_principal_user_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_policy_maker',
            field=models.BooleanField(default=False),
        ),
    ]
