# Generated by Django 5.2.7 on 2026-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_user_is_policy_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kiswate_user',
            field=models.BooleanField(default=False),
        ),
    ]
