# Generated by Django 5.2.7 on 2026-03-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_is_kiswate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kiswate_admin',
            field=models.BooleanField(default=False),
        ),
    ]
