# Generated by Django 5.2.7 on 2026-07-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiswate_digital_app', '0001_initial'),
        ('school', '0059_notification_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(blank=True, choices=[('sciences', 'Sciences'), ('mathematics', 'Mathematics'), ('languages', 'Languages'), ('humanities', 'Humanities'), ('arts', 'Arts & Creative'), ('technical', 'Technical & Vocational'), ('ict', 'ICT & Computing'), ('business', 'Business & Commerce'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='is_tuition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9'), ('grade10', 'Grade 10'), ('grade11', 'Grade 11'), ('grade12', 'Grade 12'), ('olevel', 'O-Level'), ('alevel', 'A-Level'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='school.school'),
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card')], default='mpesa', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, help_text='M-Pesa or guardian phone', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='kiswate_digital_app.enrollment')),
            ],
        ),
    ]
