# Generated by Django 5.2.7 on 2026-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiswate_digital_app', '0002_program_category_program_is_tuition_program_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('school', 'School Sponsored')], default='mpesa', max_length=10),
        ),
    ]
