# Generated by Django 5.2.7 on 2026-07-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiswate_digital_app', '0003_alter_tuitionpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to='kiswate_digital_app.userprofile'),
        ),
    ]
