# Generated by Django 5.2.7 on 2026-07-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiswate_digital_app', '0004_assessment_created_by_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='kiswate_digital_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='virtualclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_classes', to='kiswate_digital_app.userprofile'),
        ),
    ]
