# Generated by Django 5.2.7 on 2025-11-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_scanlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanLog',
        ),
    ]
