# Generated by Django 5.2.7 on 2025-11-04 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_delete_scanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartid',
            name='student',
        ),
        migrations.AddField(
            model_name='smartid',
            name='card_id',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartid',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('smart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='school.smartid')),
            ],
        ),
    ]
