# Generated by Django 5.2.7 on 2025-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_smartid_student_smartid_card_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
