# Generated by Django 5.2.7 on 2025-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_scanlog_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartid',
            name='user_f18_id',
            field=models.CharField(db_index=True, default=10, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
