# Generated by Django 5.2.7 on 2025-11-18 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_smartid_user_f18_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_canceled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('in_person', 'In-Person'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('other', 'Other')], default='in_person', max_length=50)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('class', 'By Class'), ('grade', 'By Grade'), ('school', 'Whole School')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=5)),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='virtualclass',
            name='school',
        ),
        migrations.RemoveField(
            model_name='virtualclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='virtualclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='school.staffprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('ET', 'Excused Tardy'), ('UT', 'Unexcused Tardy'), ('EA', 'Excused Absence'), ('UA', 'Unexcused Absence'), ('IB', 'Inappropriate Behavior'), ('18', 'Suspension'), ('20', 'Expulsion')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='frequency_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='linked_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_links', to='school.attendance'),
        ),
        migrations.AddField(
            model_name='disciplinerecord',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='incident_type',
            field=models.CharField(choices=[('late', 'Late Arrival'), ('misconduct', 'Misconduct'), ('absence', 'Unauthorized Absence'), ('other', 'Other')], default='misconduct', max_length=20),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='school.student'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('deputy_principal', 'Deputy Principal'), ('principal', 'Principal'), ('administrator', 'Administrator'), ('security', 'Security Staff'), ('cook', 'Cook'), ('dorm_supervisor', 'Dormitory Supervisor'), ('gate_keeper', 'School Gate Keeper'), ('trip_coordinator', 'Trip Coordinator'), ('moe_policy_maker', 'MoE Policy Maker'), ('cleaner', 'Cleaner'), ('driver', 'Driver'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='disciplinerecord',
            index=models.Index(fields=['student', 'date', 'severity'], name='school_disc_student_2deb3e_idx'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_taught', to='school.staffprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='school.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.attendance'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.disciplinerecord'),
        ),
        migrations.AddField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='role',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='school.school'),
        ),
        migrations.AddField(
            model_name='parent',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='parents', to='school.role'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='school.role'),
        ),
        migrations.AddField(
            model_name='session',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.lesson'),
        ),
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.school'),
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.subject'),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.staffprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='school.session'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'marked_at'], name='school_atte_status_f71e94_idx'),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.staffprofile'),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_reports', to='school.grade'),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_reports', to='school.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.grade'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.timetable'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='participation_score',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='virtual_class',
        ),
        migrations.AlterUniqueTogether(
            name='summaryreport',
            unique_together={('school', 'grade', 'report_type', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'grade', 'term', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('timetable', 'subject', 'date', 'start_time')},
        ),
        migrations.DeleteModel(
            name='VirtualClass',
        ),
    ]
