# Generated by Django 5.2.7 on 2025-11-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_lesson_notification_role_session_summaryreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10, null=True),
        ),
    ]
