# Generated by Django 5.2.7 on 2025-11-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_lesson_day_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parents',
        ),
    ]
