# Generated by Django 5.2.7 on 2025-11-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_rename_parent_student_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('ET', 'Excused Tardy'), ('UT', 'Unexcused Tardy'), ('EA', 'Excused Absence'), ('UA', 'Unexcused Absence'), ('IB', 'Inappropriate Behavior'), ('18', 'Suspension'), ('20', 'Expulsion')], default='P', max_length=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('scan_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.scanlog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_attendance', to='school.student')),
            ],
        ),
    ]
