# Generated by Django 5.2.7 on 2025-11-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_subcounty_constituency_remove_ward_sub_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='lessons_per_term',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='school.school')),
            ],
            options={
                'unique_together': {('grade', 'name', 'school')},
            },
        ),
    ]
