# Generated by Django 5.2.7 on 2025-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_grade_lessons_per_term_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
