# Generated by Django 5.2.7 on 2025-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_streams_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers_subjects', to='school.subject'),
        ),
    ]
