# Generated by Django 5.2.7 on 2025-11-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_subject_teacher_remove_staffprofile_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_stream', to='school.streams'),
        ),
    ]
