# Generated by Django 5.2.7 on 2025-11-27 13:35

import django.db.models.deletion
from django.db import migrations, models


def clear_invalid_terms(apps, schema_editor):
    """
    Before adding the FK constraint, ensure that all existing timetable.term
    values are set to NULL to avoid FK integrity errors.
    """
    Timetable = apps.get_model("school", "Timetable")
    Timetable.objects.update(term=None)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_student_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stream',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lessons',
                to='school.streams'
            ),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='terms',
                    to='school.school'
                )),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='timetable',
            name='term',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='term_timetables',
                to='school.term'
            ),
        ),
        migrations.RunPython(clear_invalid_terms, migrations.RunPython.noop),
    ]
