# Generated by Django 5.2.7 on 2025-11-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_lesson_stream_term_alter_timetable_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='sessions_per_week',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='timetable',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.streams'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.timetable'),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.grade'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('timetable', 'subject', 'date', 'start_time', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'grade', 'stream', 'term', 'year')},
        ),
    ]
