# Generated by Django 5.2.7 on 2025-11-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.timeslot'),
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_of_week', 'time_slot__start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('timetable', 'subject', 'day_of_week', 'time_slot', 'stream')},
        ),

        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
    ]
