# Generated by Django 5.2.7 on 2025-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_lesson_options_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
