# Generated by Django 5.2.7 on 2025-11-28 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_lesson_lesson_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day_of_week', 'lesson_date', 'time_slot__start_time']},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='school_atte_status_f71e94_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('ET', 'Excused Tardy'), ('UT', 'Unexcused Tardy'), ('EA', 'Excused Absence'), ('UA', 'Unexcused Absence'), ('IB', 'Inappropriate Behavior'), ('18', 'Suspension'), ('20', 'Expulsion')], default='present', max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
    ]
