# Generated by Django 5.2.7 on 2025-12-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeattendance',
            name='grade',
        ),
        migrations.AddField(
            model_name='gradeattendance',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.streams'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers_subjects', to='school.subject'),
        ),
    ]
