# Generated by Django 5.2.7 on 2025-12-15 10:20

import django.db.models.deletion
import school.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_remove_gradeattendance_grade_gradeattendance_stream_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file_category', models.CharField(choices=[('grade', 'Grade'), ('staff', 'Staff'), ('subjects', 'Subjects')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[school.models.validate_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('file_type', models.CharField(editable=False, max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='school.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
