# Generated by Django 5.2.7 on 2025-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_attendance_term_academicyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('ET', 'Excused Tardy'), ('UT', 'Unexcused Tardy'), ('EA', 'Excused Absence'), ('UA', 'Unexcused Absence'), ('IB', 'Inappropriate Behavior'), ('18', 'Suspension'), ('20', 'Expulsion')], default='P', max_length=20),
        ),
    ]
