# Generated by Django 5.2.7 on 2025-12-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('ET', 'Excused Tardy'), ('UT', 'Unexcused Tardy'), ('EA', 'Excused Absence'), ('UA', 'Unexcused Absence'), ('IB', 'Behavior'), ('18', 'Suspension'), ('20', 'Expulsion')], max_length=20),
        ),
    ]
