# Generated by Django 5.2.7 on 2025-12-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStreamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_stream_assignments', to='school.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='school.streams')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_streams', to='school.staffprofile')),
            ],
            options={
                'unique_together': {('teacher', 'stream', 'school')},
            },
        ),
    ]
