# Generated by Django 5.2.7 on 2025-12-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_teacherstreamassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='incident_type',
            field=models.CharField(choices=[('late', 'Late Arrival'), ('expulsion', 'Expulsion'), ('tardy', 'Tardy'), ('absence', 'Absence'), ('misconduct', 'Misconduct'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('other', 'Other')], default='misconduct', max_length=20),
        ),
    ]
