# Generated by Django 5.2.7 on 2026-01-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_alter_disciplinerecord_incident_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='subject',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_enrollments', to='school.lesson'),
        ),
    ]
