# Generated by Django 5.2.7 on 2026-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_remove_enrollment_subject_enrollment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
