# Generated by Django 5.2.7 on 2026-01-23 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_uploadedfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_alerts', to='school.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PolicymakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('county_officer', 'County Officer'), ('national', 'National'), ('other', 'Other')], max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policymaker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
