# Generated by Django 5.2.7 on 2026-01-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_subject_is_elective_pathway_student_pathway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_file_category',
            field=models.CharField(choices=[('grade', 'Grade'), ('staff', 'Staff'), ('subjects', 'Subjects'), ('timetable', 'timetable')], max_length=20),
        ),
    ]
