# Generated by Django 5.2.7 on 2026-01-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_alter_uploadedfile_upload_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_file_category',
            field=models.CharField(choices=[('grade', 'Grade'), ('users', 'users'), ('subjects', 'Subjects'), ('timetable', 'timetable')], max_length=20),
        ),
    ]
