# Generated by Django 5.2.7 on 2026-01-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_alter_uploadedfile_upload_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
