# Generated by Django 5.2.7 on 2026-01-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
