# Generated by Django 5.2.7 on 2026-01-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('timetable', 'subject', 'day_of_week', 'time_slot', 'stream', 'lesson_date')},
        ),
    ]
