# Generated by Django 5.2.7 on 2026-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(related_name='subjects', to='school.grade'),
        ),
    ]
