# Generated by Django 5.2.7 on 2026-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_remove_subject_grade_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('administrator', 'Administrator'), ('class_teacher', 'Class Teacher'), ('clerks', 'Clerks'), ('finance', 'Finance'), ('security', 'Security Staff'), ('cook', 'Cook'), ('dorm_supervisor', 'Dormitory Supervisor'), ('gate_keeper', 'School Gate Keeper'), ('trip_coordinator', 'Trip Coordinator'), ('moe_policy_maker', 'MoE Policy Maker'), ('cleaner', 'Cleaner'), ('driver', 'Driver')], max_length=100),
        ),
    ]
