# Generated by Django 5.2.7 on 2026-02-07 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_alter_staffprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
