# Generated by Django 5.2.7 on 2026-02-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_alter_parent_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_classification',
            field=models.CharField(blank=True, choices=[('C1', 'National'), ('C2', 'National'), ('C3', 'National'), ('C4', 'National')], max_length=250, null=True),
        ),
    ]
