# Generated by Django 5.2.7 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_school_school_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_classification',
            field=models.CharField(blank=True, choices=[('C1', 'National'), ('C2', 'Extra-County'), ('C3', 'County'), ('C4', 'Sub-County/Day')], max_length=250, null=True),
        ),
    ]
