# Generated by Django 5.2.7 on 2026-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_contactmessage_options_contactmessage_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
