# Generated by Django 5.2.7 on 2026-03-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_timetable_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
