# Generated by Django 5.2.7 on 2026-03-25 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_student_expelled_student_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment'], name='school_atte_enrollm_c9a3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinerecord',
            index=models.Index(fields=['teacher', 'date'], name='school_disc_teacher_3d1b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinerecord',
            index=models.Index(fields=['school', 'date'], name='school_disc_school__5883f0_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['lesson'], name='school_enro_lesson__0b899e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='school_enro_student_47cfed_idx'),
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
