# Generated by Django 5.2.7 on 2026-03-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_upload_attendance_school_atte_enrollm_c9a3d0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='school.school'),
        ),
    ]
