# Generated by Django 5.2.7 on 2026-07-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_upload_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('curriculum', models.CharField(choices=[('cbc', 'CBC (Competency-Based)'), ('kcse', 'KCSE'), ('kcpe', 'KCPE'), ('igcse', 'IGCSE'), ('other', 'Other')], default='cbc', max_length=20)),
                ('is_core', models.BooleanField(default=True, help_text='Core/mandatory subject')),
                ('is_elective', models.BooleanField(default=False)),
                ('sessions_per_week_default', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Catalog',
                'verbose_name_plural': 'Subject Catalog',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='catalog_ref',
            field=models.ForeignKey(blank=True, help_text='Platform catalog entry this subject was activated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subjects', to='school.subjectcatalog'),
        ),
    ]
