# Generated by Django 5.2.7 on 2026-07-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_add_announcement_feeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
