# Generated by Django 5.2.7 on 2026-07-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_notification_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='result_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
