# Generated by Django 5.2.7 on 2026-07-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_upload_background_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('cat_out_of', models.FloatField(default=30.0)),
                ('assignment_out_of', models.FloatField(default=10.0)),
                ('assessment_out_of', models.FloatField(default=10.0)),
                ('exam_out_of', models.FloatField(default=50.0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions_created', to='school.staffprofile')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='school.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='school.term')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_score', models.FloatField(blank=True, null=True)),
                ('assignment_score', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results_entered', to='school.staffprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.streams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='school.subject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='school.examsession')),
            ],
            options={
                'ordering': ['student__user__last_name', 'student__user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['school', 'year', 'is_published'], name='school_exam_school__2efcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['session', 'stream'], name='school_exam_session_2f501c_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['session', 'subject'], name='school_exam_session_886182_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'session'], name='school_exam_student_1b2bd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('session', 'student', 'subject')},
        ),
    ]
