# Generated by Django 5.2.7 on 2026-07-13 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_exam_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('development', 'Development Levy'), ('activity', 'Activity Fee'), ('boarding', 'Boarding Fee'), ('transport', 'Transport Fee'), ('uniform', 'Uniform Fee'), ('exam', 'Exam Fee'), ('other', 'Other')], default='tuition', max_length=20)),
                ('description', models.CharField(default='School Fees', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='school.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures_created', to='school.staffprofile')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.school')),
                ('stream', models.ForeignKey(blank=True, help_text='Leave blank to apply to all streams in the grade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.streams')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.term')),
            ],
            options={
                'ordering': ['grade__name', 'fee_type'],
                'indexes': [models.Index(fields=['school', 'term', 'is_active'], name='school_fees_school__c0f6c0_idx')],
                'unique_together': {('school', 'grade', 'stream', 'term', 'fee_type')},
            },
        ),
    ]
