# Generated by Django 5.2.7 on 2026-07-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0065_feetype_feestructure_fee_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'school')},
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ct_assignments_made', to='school.staffprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='school.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='school.streams')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_streams', to='school.staffprofile')),
            ],
            options={
                'unique_together': {('stream', 'school')},
            },
        ),
    ]
