# Generated by Django 5.2.7 on 2026-07-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_class_teacher_role_and_assignment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complaint',
            name='school_comp_parent__ce252d_idx',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('student', 'Student'), ('principal', 'Principal / Admin')], default='parent', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_complaints', to='school.student'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='target',
            field=models.CharField(choices=[('school_admin', 'School Administration'), ('kiswate_admin', 'Kiswate Support')], default='school_admin', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='teacher_complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_complaints', to='school.staffprofile'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('discipline', 'Discipline'), ('fees', 'Fees'), ('health', 'Health & Safety'), ('bullying', 'Bullying'), ('teacher', 'Teacher Conduct'), ('facilities', 'Facilities'), ('workplace', 'Workplace Issue'), ('policy', 'Policy & Platform'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='school.parent'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['school', 'target'], name='school_comp_school__8279a4_idx'),
        ),
    ]
