from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(School)
admin.site.register(Role)
admin.site.register(Timetable)
admin.site.register(Lesson)
admin.site.register(Grade)
admin.site.register(StaffProfile)
admin.site.register(Student)
admin.site.register(Parent)
admin.site.register(Subject)
admin.site.register(SmartID)
admin.site.register(Payment)
admin.site.register(Attendance)
admin.site.register(Enrollment)
admin.site.register(Assignment)
admin.site.register(Session)
admin.site.register(Submission)
admin.site.register(Certificate)
admin.site.register(DisciplineRecord)
admin.site.register(Book)
admin.site.register(Chapter)
admin.site.register(LibraryAccess)
admin.site.register(ScholarshipDisbursement)
admin.site.register(ScholarshipApplication)
admin.site.register(Invoice)
admin.site.register(SubscriptionPlan)
admin.site.register(SchoolSubscription)
admin.site.register(ScanLog)
admin.site.register(SummaryReport)
admin.site.register(Notification)